language: python
sudo: false
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"
env:
 - DJANGO_VERSION="1.8"
 - DJANGO_VERSION="1.9"
install:
 - pip install -q "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99" -r travis.txt
script: coverage run run.py test
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION="1.9"
after_success:
 - coveralls
 - codecov
