language: python

sudo: false

dist: xenial

matrix:
  include:
      - { python: "2.7", env: TOXENV=py27-django111-jinja }

      - { python: "3.5", env: TOXENV=py35-django111-jinja }

      - { python: "3.6", env: TOXENV=py36-django111-jinja }
      - { python: "3.6", env: TOXENV=py36-django22-jinja }
      - { python: "3.6", env: TOXENV=py36-django30 }

      - { python: "3.7", env: TOXENV=py37-django22-jinja }
      - { python: "3.7", env: TOXENV=py37-django30 }

      - { python: "3.8", env: TOXENV=py38-django22-jinja }
      - { python: "3.8", env: TOXENV=py38-django30 }

      - { python: "3.8", env: TOXENV=i18n }

install:
  - pip install tox tox-travis

# Some tests may require accessing the database from multiple threads
# (see #296), which isn't supported by the sqlite3 engine. Run the tests with
# Postgres in CI to allow full test coverage.
services:
  postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database waffle_test;' -U postgres

env:
  - DATABASE_URL=postgres://postgres@localhost:5432/waffle_test

script:
  - tox

deploy:
  provider: pypi
  user: django-waffle
  password:
    secure: sQzN+jn7JdkIJbXsjS1uRueNVo2AsPh2iJChDAisWu8qFRMFREbHCKRu33+WZ9Vbw0NuRC2Wl2DknPTKYBtMq+4YzbKyRLAXvf/qAzWwcbjQsPAz1bQnfDBbOhcewiltfVf3AEbsq97NdKhOS4+T0R3/eqMhbAM9PVP2WO78cvA=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.7
    env: TOXENV=i18n
