language: python
python:
 - 2.6
 - 2.7
 - 3.3
env:
 - DJANGO_VERSION=1.4.9
 - DJANGO_VERSION=1.5.5
install:
 - pip install -q Django==${DJANGO_VERSION} -r travis.txt --use-mirrors
script: invoke test
matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=1.4.9
