language: python
sudo: false
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
env:
 - DJANGO_VERSION=1.4 JINJA_WITH="jingo>=0.7.1,<0.8"
 - DJANGO_VERSION=1.6 JINJA_WITH="jingo>=0.7.1,<0.8"
 - DJANGO_VERSION=1.7 JINJA_WITH="jingo>=0.8"
 - DJANGO_VERSION=1.8
 - DJANGO_VERSION=1.9
install:
 - pip install -q "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99" "${JINJA_WITH}" -r travis.txt
script: ./run.sh test
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=1.7 JINJA_WITH="jingo>=0.8"
    - python: "2.6"
      env: DJANGO_VERSION=1.8
    - python: "2.6"
      env: DJANGO_VERSION=1.9
    - python: "3.3"
      env: DJANGO_VERSION=1.4 JINJA_WITH="jingo>=0.7.1,<0.8"
    - python: "3.4"
      env: DJANGO_VERSION=1.4 JINJA_WITH="jingo>=0.7.1,<0.8"
